import layout from '../components/layout.js';
import personalNotes from '../components/personal-notes.js';
import { experience } from '../data/profile.js';
import { escape as e } from '../components/utils.js';
export default class {
  data() { return { permalink: 'about/index.html' }; }
  render() {
    const experienceMarkup = experience.map(job => `<article><div class="job-date">${e(job.dates)}</div><div><h3>${e(job.company)}</h3><p class="job-role">${e(job.role)}</p><p>${e(job.text)}</p></div></article>`).join('');
    return layout({title: 'A little more about me', path: '/about/', description: 'Aryan Basantani’s path through computer science, finance, product building, and consulting—and the interests behind the work.', content: `<section class="page-intro about-intro"><p class="eyebrow">A little more about me</p><h1>A few paths.<br /> <em>A clearer direction.</em></h1><p>I’ve tried product, finance, and consulting. The work I keep coming back to puts me close to users and engineers, with enough ownership to build, measure, and improve.</p></section>
  <div class="narrative-layout"><aside><span class="eyebrow">The short story</span><p>Computer science<br /> Financial curiosity<br /> Product ownership</p></aside><div class="narrative"><p>I studied Computer Science with a minor in Finance at BITS Pilani, Hyderabad Campus. I was drawn to ambiguous business problems and the ways technology could help solve them. Working with early-stage startups through the consulting group gave me an early view of product design, go-to-market decisions, and customer needs.</p><p>At JPMorgan, I worked on an internal platform for wholesale credit-risk analysis. Financial models, automation, migrations, and conversations with credit officers taught me why accuracy and trust matter so much in financial systems. I pursued the CFA and FRM exams to build deeper domain knowledge alongside the product work.</p><p>MoveInSync gave me the ownership I was looking for. As an early member of a new manufacturing-focused business unit, I worked across product, analytics, and customer operations—sometimes writing the requirements, sometimes building the first rough tool, and often working through the issue directly with a customer.</p><p>I explored consulting at Kearney to broaden that perspective. It taught me structured problem-solving and how to communicate technical trade-offs to senior stakeholders. It also clarified what I want next: long-term ownership, close collaboration with users and engineers, and the chance to keep improving what I ship.</p><p class="narrative-pull">“I like sitting close to the problem.”<span>From my LinkedIn introduction</span></p></div></div>
  <section class="section" aria-labelledby="experience-title"><div class="section-heading"><div><p class="eyebrow">Selected experience</p><h2 id="experience-title">The places<br /> <em>I’ve learned by doing.</em></h2></div></div><div class="experience-list">${experienceMarkup}</div></section>
  <section class="section foundation" aria-labelledby="foundation-title"><div><p class="eyebrow">Education & credentials</p><h2 id="foundation-title">A technical base.<br /> <em>A financial lens.</em></h2><p>BITS Pilani, Hyderabad Campus<br /> B.E. Computer Science · Minor in Finance<br /> 2020–2024</p></div><dl><div><dt>Overall CGPA</dt><dd>8.52 <span>/ 10</span></dd></div><div><dt>Finance minor GPA</dt><dd>9.67 <span>/ 10</span></dd></div><div><dt>CFA Program</dt><dd class="credential-text">Level II cleared</dd></div><div><dt>FRM exams</dt><dd class="credential-text">Parts I & II cleared</dd></div><div><dt>Additional</dt><dd class="credential-text">Bloomberg Market Concepts</dd></div></dl></section>
  <section class="section community"><p class="eyebrow">Building with other people</p><h2>Good work<br /> <em>can make room for others.</em></h2><div><p>As Vice President of BITS Hyderabad Consulting Group, I launched ProdEezy on one campus and scaled it to three, connecting 300+ students with 20+ product mentors. I also co-authored the first BITS consulting casebook.</p><p>As Secretary of the Wall Street Club, I led a 90-member finance community and launched its first newsletter, <i>Upside</i>. I was part of BlockSoc’s founding team, and supported 650+ students as a teaching assistant in Economics and Derivatives.</p></div><a class="text-link" href="/work/#communities">Explore the community work →</a></section>
  ${personalNotes()}`});
  }
}
