import { escape } from './utils.js';
const drawings = {
  "analytics": "<div class=\"analytics-drawing\"><div class=\"drawing-label\">ONE VIEW / THREE TRANSPORT PRODUCTS</div><div class=\"actor-grid\"><div><span class=\"actor-dot\"></span><strong>ETS Cab</strong><br /> Dynamic routes</div><div><span class=\"actor-dot\"></span><strong>Shuttle</strong><br /> Fixed routes</div><div><span class=\"actor-dot\"></span><strong>Rentlz</strong><br /> Ad-hoc trips</div></div><div class=\"connectors\" aria-hidden=\"true\"><i></i><i></i><i></i></div><div class=\"shared-layer\"><span>Consistent metrics & connected reports</span><small>one vertical-specific analytics suite</small></div><div class=\"output-row\"><span>Dashboard metric</span><span>↓ Individual record</span></div><span class=\"drawing-footnote\">Scope schematic · reconstructed from my project account</span></div>",
  "commerce": "<figure class=\"commerce-drawing\"><img src=\"/media/shubh-storefront.jpg\" alt=\"Festive clothing artwork used in the supplied Shubh Bazaar storefront\" width=\"1920\" height=\"1088\" loading=\"lazy\" decoding=\"async\" /><div class=\"commerce-wordmark\">Shubh<span>WHOLESALE BAZAAR</span></div><figcaption>Storefront artwork · supplied project asset</figcaption></figure>",
  "credit": "<div class=\"credit-drawing\"><span class=\"drawing-label\">A WORKFLOW BUILT ON TRUST</span><div class=\"workflow-step\"><span>01</span><div>Financial statements<small>Specialised portfolios</small></div></div><div class=\"workflow-step\"><span>02</span><div>Structured models<small>A shared analytical platform</small></div></div><div class=\"workflow-step\"><span>03</span><div>Credit analysis & reporting<small>VBA automation · preserved output format</small></div></div><span class=\"drawing-footnote\">Workflow schematic · no proprietary records</span></div>",
  "research": "<div class=\"research-drawing\"><span class=\"drawing-label\">RESEARCH UNIVERSE / SEMICONDUCTORS</span><div class=\"company-row\"><span>NVIDIA</span><span>Intel</span><span>AMD</span></div><div class=\"research-rule\"></div><div class=\"research-columns\"><div><span>01</span><strong>Industry</strong><small>Dynamics & supply chains</small></div><div><span>02</span><strong>Business</strong><small>Competitive positioning</small></div><div><span>03</span><strong>Value</strong><small>Staged DCF</small></div></div><span class=\"drawing-footnote\">Documented research approach · no simulated results</span></div>",
  "planning": "<div class=\"planning-drawing\"><span class=\"drawing-label\">FROM FINANCIAL CONCEPT TO FEATURE</span><div class=\"planning-sheets\"><div><span>01 / PLANNING</span><strong>Goal<br /> <em>calculator</em></strong><div class=\"sheet-rule\"></div></div><div><span>02 / PROFILING</span><strong>Risk<br /> <em>profiler</em></strong><div class=\"sheet-rule\"></div></div></div><span class=\"drawing-footnote\">Feature scope · not a client-interface reproduction</span></div>"
};
export default function workVisual(kind, large = false) {
  return `<div class="work-visual visual-${escape(kind)}${large ? ' large' : ''}">${drawings[kind] || ''}</div>`;
}
